# Generated by Django 2.2.4 on 2020-07-26 17:37

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.owner, owner_phone_pure=owner.owner_phone_pure)
        for flat in flats:
            owner.flats.add(flat)
        owner.save()


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_auto_20200726_1747'),
    ]

    operations = [
        migrations.RunPython(migrate_owners, move_backward),
    ]
